# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/armon/consul-api"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.4.2"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.3.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/getsentry/sentry-go"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.6"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  version = "1.0.0"

[[constraint]]
  name = "github.com/inconshreveable/mousetrap"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.11"

[[constraint]]
  name = "github.com/jinzhu/inflection"
  version = "1.0.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.8"

[[constraint]]
  name = "github.com/konsorten/go-windows-terminal-sequences"
  version = "1.0.2"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.1"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/modern-go/concurrent"
  version = "1.0.3"

[[constraint]]
  name = "github.com/modern-go/reflect2"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.5.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.2"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/jwalterweatherman"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/xordataexchange/crypt"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.4.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.2"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/alexcesaro/quotedprintable.v3"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  branch = "v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.4"

[prune]
  go-tests = true
  unused-packages = true
